using KBS.CreditAppSys.Application.Features.CreditApplications.Queries.GetList;

namespace KBS.CreditAppSys.Application.Features.CreditApplications.Queries.GetById;
public record GetByIdCreditApplicationQueryResponse : GetListCreditApplicationQueryResponse;